### ISSUE TITLE
wrong continuation signal in sage doctests

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1235]
Source

```
        <sage doctest="not tested">
          <input>p=
q=
f=inverse_mod(e,(p-1)*(q-1))
f</input>
          <output></output>
        </sage>
```
yields
```
~~~~~~~~~~~~~~~~~~~~~~ ::

    sage: p=
    sage: q=
    sage: f=inverse_mod(e,(p-1)*(q-1))
    sage: f   # not tested
```

But the syntax should really be something like
```
    sage: p=
    ....: q=
    ....: f=inverse_mod(e,(p-1)*(q-1))
    ....: f   # not tested
```

See also #1234, which this might solve.  However, this is a more general issue preventing doctests from being as useful as they could be - imagine a `print()` in the middle of the lines and you will see what I mean.

**Comment by kcrisman** [comment]
I've narrowed this down.  Multiline commands with indentation do have this continuation marker, getting it from
```
            <xsl:when test="not(string-length($first-line))">
                <xsl:text>    ....: </xsl:text>
            </xsl:when>
            <!-- leading blank indicates continuation -->
            <xsl:when test="substring($first-line,1,1)=' '">
                <xsl:text>    ....: </xsl:text>
            </xsl:when>
```
in `mathbook-sage-doctest.xsl`.

But because of the way Sage cells are structured in "live" examples, we do need to test them in a similar way.  However, I'm not sure whether Sage's doctest framework can handle that, need to investigate what the "right" solution to this is.  Probably asking authors to change cells is not, since this should a service, but the irony in one of said authors trying to find a PTX solution is not lost on me 😉 I'll try to keep thinking about this and experimenting.

**Comment by kcrisman** [comment]
In particular, the code
```
            <!-- otherwise, totally outdented, needs sage prompt -->
            <xsl:otherwise>
                <xsl:text>    sage: </xsl:text>
            </xsl:otherwise>
```
does this, as commented.  Good work commenting @rbeezer 👍 

Unfortunately when testing a naive solution, I get
```
**********************************************************************
File "test.py", line 61, in test
Failed example:
    print(encode('cb'))
    print(decode(3+26*2))
Exception raised:
    Traceback (most recent call last):
      File "/Applications/SageMath-9.0.app/Contents/Resources/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Applications/SageMath-9.0.app/Contents/Resources/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1121, in compile_and_execute
        compiled = compiler(example)
      File "/Applications/SageMath-9.0.app/Contents/Resources/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 649, in compiler
        compileflags, 1)
      File "<doctest test[5]>", line 1
        print(encode('cb'))
                          ^
    SyntaxError: multiple statements found while compiling a single statement
```

So something more sophisticated might be necessary.

**Comment by rbeezer** [comment]
I can't dig into this too deep right now, but I have a suspicion about the root problem.

I assume a Sage Cell has output that is the value of the last line.  I think this is from the way the old Sage Notebook behaved.  So a `print()` in the middle does not fit that expectation.  If I wanted that behavior I would end the cell there and pick up again in the next cell.

And `p=` is invalid Python syntax, no?  I can see what is going on, but I'm not sure that should be supported.  It is really a poor-man's "interactive", no?  So, like all of PreTeXt, not every scenario is/will be supported.  Just because a "sage" is runnable (with an intermediate `print()` for example) does not mean the automatic construction of a doctest will support that use.

With all that in mind, what here needs to change to support expected use?

**Comment by kcrisman** [comment]
I assume a Sage Cell has output that is the value of the last line. I think
> this is from the way the old Sage Notebook behaved.
>

Correct, in general.


> So a print() in the middle does not fit that expectation. If I wanted
> that behavior I would end the cell there and pick up again in the next cell.
>

No, `print` statements (sagenb is Python 2, so statements) always were
expected to print out in Sage notebooks.  That is what `print` does, after
all, anywhere.

It is very, very useful in interacts, actually, but also it means one can
have a lot of stuff in a cell with just one "evaluate", which is definitely
a consideration - Sage cells do not take up arbitrarily small amount of
screen space.  I don't see why this wouldn't be a normal expectation of a
Sage cell, and hence should someone be doctested.

Also, if one had
```
a = 3
a
2*a
```
then one should expect only one output, `6`, not the two outputs the
current translation would give.  I admit I'm not so sure what the "best"
way to handle this is, and there is no rush, I just happened to want to
record all the stuff I found yesterday.



> And p= is invalid Python syntax, no?
>

I hope I didn't cut and paste that error - that particular one should be
not tested, it was indeed supposed to be a poor man's interact - so that
people actually learn to TYPE!   But not relevant, if I recall correctly.
